/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef T_TEST_EMPTY_SERVICE_H
#define T_TEST_EMPTY_SERVICE_H

#include "t_test_debug_proto_test_types.h"

/* EmptyService service interface */
typedef struct _TTestEmptyServiceIf TTestEmptyServiceIf;  /* dummy object */

struct _TTestEmptyServiceIfInterface
{
  GTypeInterface parent;

};
typedef struct _TTestEmptyServiceIfInterface TTestEmptyServiceIfInterface;

GType t_test_empty_service_if_get_type (void);
#define T_TEST_TYPE_EMPTY_SERVICE_IF (t_test_empty_service_if_get_type())
#define T_TEST_EMPTY_SERVICE_IF(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), T_TEST_TYPE_EMPTY_SERVICE_IF, TTestEmptyServiceIf))
#define T_TEST_IS_EMPTY_SERVICE_IF(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), T_TEST_TYPE_EMPTY_SERVICE_IF))
#define T_TEST_EMPTY_SERVICE_IF_GET_INTERFACE(inst) (G_TYPE_INSTANCE_GET_INTERFACE ((inst), T_TEST_TYPE_EMPTY_SERVICE_IF, TTestEmptyServiceIfInterface))


/* EmptyService service client */
struct _TTestEmptyServiceClient
{
  GObject parent;

  ThriftProtocol *input_protocol;
  ThriftProtocol *output_protocol;
};
typedef struct _TTestEmptyServiceClient TTestEmptyServiceClient;

struct _TTestEmptyServiceClientClass
{
  GObjectClass parent;
};
typedef struct _TTestEmptyServiceClientClass TTestEmptyServiceClientClass;

GType t_test_empty_service_client_get_type (void);
#define T_TEST_TYPE_EMPTY_SERVICE_CLIENT (t_test_empty_service_client_get_type())
#define T_TEST_EMPTY_SERVICE_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), T_TEST_TYPE_EMPTY_SERVICE_CLIENT, TTestEmptyServiceClient))
#define T_TEST_EMPTY_SERVICE_CLIENT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), T_TEST_TYPE_EMPTY_SERVICE_CLIENT, TTestEmptyServiceClientClass))
#define T_TEST_EMPTY_SERVICE_IS_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), T_TEST_TYPE_EMPTY_SERVICE_CLIENT))
#define T_TEST_EMPTY_SERVICE_IS_CLIENT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), T_TEST_TYPE_EMPTY_SERVICE_CLIENT))
#define T_TEST_EMPTY_SERVICE_CLIENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), T_TEST_TYPE_EMPTY_SERVICE_CLIENT, TTestEmptyServiceClientClass))

void empty_service_client_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec);
void empty_service_client_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec);

#endif /* T_TEST_EMPTY_SERVICE_H */
