/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include <string.h>
#include <thrift/c_glib/thrift.h>
#include <thrift/c_glib/thrift_application_exception.h>
#include "t_test_empty_service.h"

GType
t_test_empty_service_if_get_type (void)
{
  static GType type = 0;
  if (type == 0)
  {
    static const GTypeInfo type_info =
    {
      sizeof (TTestEmptyServiceIfInterface),
      NULL,  /* base_init */
      NULL,  /* base_finalize */
      NULL,  /* class_init */
      NULL,  /* class_finalize */
      NULL,  /* class_data */
      0,     /* instance_size */
      0,     /* n_preallocs */
      NULL,  /* instance_init */
      NULL   /* value_table */
    };
    type = g_type_register_static (G_TYPE_INTERFACE,
                                   "TTestEmptyServiceIf",
                                   &type_info, 0);
  }
  return type;
}

static void 
t_test_empty_service_if_interface_init (TTestEmptyServiceIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (TTestEmptyServiceClient, t_test_empty_service_client,
                       G_TYPE_OBJECT, 
                         G_IMPLEMENT_INTERFACE (T_TEST_TYPE_EMPTY_SERVICE_IF,
                                                t_test_empty_service_if_interface_init));

enum _TTestEmptyServiceClientProperties
{
  PROP_0,
  PROP_T_TEST_EMPTY_SERVICE_CLIENT_INPUT_PROTOCOL,
  PROP_T_TEST_EMPTY_SERVICE_CLIENT_OUTPUT_PROTOCOL
};

void
t_test_empty_service_client_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec)
{
  TTestEmptyServiceClient *client = T_TEST_EMPTY_SERVICE_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_T_TEST_EMPTY_SERVICE_CLIENT_INPUT_PROTOCOL:
      client->input_protocol = g_value_get_object (value);
      break;
    case PROP_T_TEST_EMPTY_SERVICE_CLIENT_OUTPUT_PROTOCOL:
      client->output_protocol = g_value_get_object (value);
      break;
  }
}

void
t_test_empty_service_client_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec)
{
  TTestEmptyServiceClient *client = T_TEST_EMPTY_SERVICE_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_T_TEST_EMPTY_SERVICE_CLIENT_INPUT_PROTOCOL:
      g_value_set_object (value, client->input_protocol);
      break;
    case PROP_T_TEST_EMPTY_SERVICE_CLIENT_OUTPUT_PROTOCOL:
      g_value_set_object (value, client->output_protocol);
      break;
  }
}

static void
t_test_empty_service_if_interface_init (TTestEmptyServiceIfInterface *iface)
{
}

static void
t_test_empty_service_client_init (TTestEmptyServiceClient *client)
{
  client->input_protocol = NULL;
  client->output_protocol = NULL;
}

static void
t_test_empty_service_client_class_init (TTestEmptyServiceClientClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->set_property = t_test_empty_service_client_set_property;
  gobject_class->get_property = t_test_empty_service_client_get_property;

  param_spec = g_param_spec_object ("input_protocol",
                                    "input protocol (construct)",
                                    "Set the client input protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_T_TEST_EMPTY_SERVICE_CLIENT_INPUT_PROTOCOL, param_spec);

  param_spec = g_param_spec_object ("output_protocol",
                                    "output protocol (construct)",
                                    "Set the client output protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_T_TEST_EMPTY_SERVICE_CLIENT_OUTPUT_PROTOCOL, param_spec);
}

