/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef T_TEST_INHERITED_H
#define T_TEST_INHERITED_H

#include "t_test_debug_proto_test_types.h"
#include "t_test_srv.h"

/* Inherited service interface */
typedef struct _TTestInheritedIf TTestInheritedIf;  /* dummy object */

struct _TTestInheritedIfInterface
{
  GTypeInterface parent;

  gboolean (*identity) (TTestInheritedIf *iface, gint32* _return, const gint32 arg, GError **error);
};
typedef struct _TTestInheritedIfInterface TTestInheritedIfInterface;

GType t_test_inherited_if_get_type (void);
#define T_TEST_TYPE_INHERITED_IF (t_test_inherited_if_get_type())
#define T_TEST_INHERITED_IF(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), T_TEST_TYPE_INHERITED_IF, TTestInheritedIf))
#define T_TEST_IS_INHERITED_IF(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), T_TEST_TYPE_INHERITED_IF))
#define T_TEST_INHERITED_IF_GET_INTERFACE(inst) (G_TYPE_INSTANCE_GET_INTERFACE ((inst), T_TEST_TYPE_INHERITED_IF, TTestInheritedIfInterface))

gboolean t_test_inherited_if_identity (TTestInheritedIf *iface, gint32* _return, const gint32 arg, GError **error);

/* Inherited service client */
struct _TTestInheritedClient
{
  GObject parent;

  ThriftProtocol *input_protocol;
  ThriftProtocol *output_protocol;
};
typedef struct _TTestInheritedClient TTestInheritedClient;

struct _TTestInheritedClientClass
{
  GObjectClass parent;
};
typedef struct _TTestInheritedClientClass TTestInheritedClientClass;

GType t_test_inherited_client_get_type (void);
#define T_TEST_TYPE_INHERITED_CLIENT (t_test_inherited_client_get_type())
#define T_TEST_INHERITED_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), T_TEST_TYPE_INHERITED_CLIENT, TTestInheritedClient))
#define T_TEST_INHERITED_CLIENT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), T_TEST_TYPE_INHERITED_CLIENT, TTestInheritedClientClass))
#define T_TEST_INHERITED_IS_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), T_TEST_TYPE_INHERITED_CLIENT))
#define T_TEST_INHERITED_IS_CLIENT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), T_TEST_TYPE_INHERITED_CLIENT))
#define T_TEST_INHERITED_CLIENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), T_TEST_TYPE_INHERITED_CLIENT, TTestInheritedClientClass))

gboolean t_test_inherited_client_identity (TTestInheritedIf * iface, gint32* _return, const gint32 arg, GError ** error);
gboolean t_test_inherited_client_send_identity (TTestInheritedIf * iface, const gint32 arg, GError ** error);
gboolean t_test_inherited_client_recv_identity (TTestInheritedIf * iface, gint32* _return, GError ** error);
void inherited_client_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec);
void inherited_client_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec);

#endif /* T_TEST_INHERITED_H */
