/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef T_TEST_REVERSE_ORDER_SERVICE_H
#define T_TEST_REVERSE_ORDER_SERVICE_H

#include "t_test_debug_proto_test_types.h"

/* ReverseOrderService service interface */
typedef struct _TTestReverseOrderServiceIf TTestReverseOrderServiceIf;  /* dummy object */

struct _TTestReverseOrderServiceIfInterface
{
  GTypeInterface parent;

  gboolean (*my_method) (TTestReverseOrderServiceIf *iface, const gchar * first, const gint16 second, const gint32 third, const gint64 fourth, GError **error);
};
typedef struct _TTestReverseOrderServiceIfInterface TTestReverseOrderServiceIfInterface;

GType t_test_reverse_order_service_if_get_type (void);
#define T_TEST_TYPE_REVERSE_ORDER_SERVICE_IF (t_test_reverse_order_service_if_get_type())
#define T_TEST_REVERSE_ORDER_SERVICE_IF(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), T_TEST_TYPE_REVERSE_ORDER_SERVICE_IF, TTestReverseOrderServiceIf))
#define T_TEST_IS_REVERSE_ORDER_SERVICE_IF(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), T_TEST_TYPE_REVERSE_ORDER_SERVICE_IF))
#define T_TEST_REVERSE_ORDER_SERVICE_IF_GET_INTERFACE(inst) (G_TYPE_INSTANCE_GET_INTERFACE ((inst), T_TEST_TYPE_REVERSE_ORDER_SERVICE_IF, TTestReverseOrderServiceIfInterface))

gboolean t_test_reverse_order_service_if_my_method (TTestReverseOrderServiceIf *iface, const gchar * first, const gint16 second, const gint32 third, const gint64 fourth, GError **error);

/* ReverseOrderService service client */
struct _TTestReverseOrderServiceClient
{
  GObject parent;

  ThriftProtocol *input_protocol;
  ThriftProtocol *output_protocol;
};
typedef struct _TTestReverseOrderServiceClient TTestReverseOrderServiceClient;

struct _TTestReverseOrderServiceClientClass
{
  GObjectClass parent;
};
typedef struct _TTestReverseOrderServiceClientClass TTestReverseOrderServiceClientClass;

GType t_test_reverse_order_service_client_get_type (void);
#define T_TEST_TYPE_REVERSE_ORDER_SERVICE_CLIENT (t_test_reverse_order_service_client_get_type())
#define T_TEST_REVERSE_ORDER_SERVICE_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), T_TEST_TYPE_REVERSE_ORDER_SERVICE_CLIENT, TTestReverseOrderServiceClient))
#define T_TEST_REVERSE_ORDER_SERVICE_CLIENT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), T_TEST_TYPE_REVERSE_ORDER_SERVICE_CLIENT, TTestReverseOrderServiceClientClass))
#define T_TEST_REVERSE_ORDER_SERVICE_IS_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), T_TEST_TYPE_REVERSE_ORDER_SERVICE_CLIENT))
#define T_TEST_REVERSE_ORDER_SERVICE_IS_CLIENT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), T_TEST_TYPE_REVERSE_ORDER_SERVICE_CLIENT))
#define T_TEST_REVERSE_ORDER_SERVICE_CLIENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), T_TEST_TYPE_REVERSE_ORDER_SERVICE_CLIENT, TTestReverseOrderServiceClientClass))

gboolean t_test_reverse_order_service_client_my_method (TTestReverseOrderServiceIf * iface, const gchar * first, const gint16 second, const gint32 third, const gint64 fourth, GError ** error);
gboolean t_test_reverse_order_service_client_send_my_method (TTestReverseOrderServiceIf * iface, const gchar * first, const gint16 second, const gint32 third, const gint64 fourth, GError ** error);
gboolean t_test_reverse_order_service_client_recv_my_method (TTestReverseOrderServiceIf * iface, GError ** error);
void reverse_order_service_client_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec);
void reverse_order_service_client_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec);

#endif /* T_TEST_REVERSE_ORDER_SERVICE_H */
