/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift.test;

import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class DebugProtoTestConstants {

  public static final CompactProtoTestStruct COMPACT_TEST = new CompactProtoTestStruct();
  static {
    COMPACT_TEST.setA_byte((byte)127);
    COMPACT_TEST.setA_i16((short)32000);
    COMPACT_TEST.setA_i32(1000000000);
    COMPACT_TEST.setA_i64(1099511627775L);
    COMPACT_TEST.setA_double(5.6789);
    COMPACT_TEST.setA_string("my string");
    COMPACT_TEST.setTrue_field(true);
    COMPACT_TEST.setFalse_field(false);
    Empty tmp716 = new Empty();

    COMPACT_TEST.setEmpty_struct_field(tmp716);
    List<Byte> tmp717 = new ArrayList<Byte>();
    tmp717.add((byte)-127);
    tmp717.add((byte)-1);
    tmp717.add((byte)0);
    tmp717.add((byte)1);
    tmp717.add((byte)127);

    COMPACT_TEST.setByte_list(tmp717);
    List<Short> tmp718 = new ArrayList<Short>();
    tmp718.add((short)-1);
    tmp718.add((short)0);
    tmp718.add((short)1);
    tmp718.add((short)32767);

    COMPACT_TEST.setI16_list(tmp718);
    List<Integer> tmp719 = new ArrayList<Integer>();
    tmp719.add(-1);
    tmp719.add(0);
    tmp719.add(255);
    tmp719.add(65535);
    tmp719.add(16777215);
    tmp719.add(2147483647);

    COMPACT_TEST.setI32_list(tmp719);
    List<Long> tmp720 = new ArrayList<Long>();
    tmp720.add(-1L);
    tmp720.add(0L);
    tmp720.add(255L);
    tmp720.add(65535L);
    tmp720.add(16777215L);
    tmp720.add(4294967295L);
    tmp720.add(1099511627775L);
    tmp720.add(281474976710655L);
    tmp720.add(72057594037927935L);
    tmp720.add(9223372036854775807L);

    COMPACT_TEST.setI64_list(tmp720);
    List<Double> tmp721 = new ArrayList<Double>();
    tmp721.add(0.1);
    tmp721.add(0.2);
    tmp721.add(0.3);

    COMPACT_TEST.setDouble_list(tmp721);
    List<String> tmp722 = new ArrayList<String>();
    tmp722.add("first");
    tmp722.add("second");
    tmp722.add("third");

    COMPACT_TEST.setString_list(tmp722);
    List<Boolean> tmp723 = new ArrayList<Boolean>();
    tmp723.add(true);
    tmp723.add(true);
    tmp723.add(true);
    tmp723.add(false);
    tmp723.add(false);
    tmp723.add(false);

    COMPACT_TEST.setBoolean_list(tmp723);
    List<Empty> tmp724 = new ArrayList<Empty>();
    Empty tmp725 = new Empty();

    tmp724.add(tmp725);
    Empty tmp726 = new Empty();

    tmp724.add(tmp726);

    COMPACT_TEST.setStruct_list(tmp724);
    Set<Byte> tmp727 = new HashSet<Byte>();
    tmp727.add((byte)-127);
    tmp727.add((byte)-1);
    tmp727.add((byte)0);
    tmp727.add((byte)1);
    tmp727.add((byte)127);

    COMPACT_TEST.setByte_set(tmp727);
    Set<Short> tmp728 = new HashSet<Short>();
    tmp728.add((short)-1);
    tmp728.add((short)0);
    tmp728.add((short)1);
    tmp728.add((short)32767);

    COMPACT_TEST.setI16_set(tmp728);
    Set<Integer> tmp729 = new HashSet<Integer>();
    tmp729.add(1);
    tmp729.add(2);
    tmp729.add(3);

    COMPACT_TEST.setI32_set(tmp729);
    Set<Long> tmp730 = new HashSet<Long>();
    tmp730.add(-1L);
    tmp730.add(0L);
    tmp730.add(255L);
    tmp730.add(65535L);
    tmp730.add(16777215L);
    tmp730.add(4294967295L);
    tmp730.add(1099511627775L);
    tmp730.add(281474976710655L);
    tmp730.add(72057594037927935L);
    tmp730.add(9223372036854775807L);

    COMPACT_TEST.setI64_set(tmp730);
    Set<Double> tmp731 = new HashSet<Double>();
    tmp731.add(0.1);
    tmp731.add(0.2);
    tmp731.add(0.3);

    COMPACT_TEST.setDouble_set(tmp731);
    Set<String> tmp732 = new HashSet<String>();
    tmp732.add("first");
    tmp732.add("second");
    tmp732.add("third");

    COMPACT_TEST.setString_set(tmp732);
    Set<Boolean> tmp733 = new HashSet<Boolean>();
    tmp733.add(true);
    tmp733.add(false);

    COMPACT_TEST.setBoolean_set(tmp733);
    Set<Empty> tmp734 = new HashSet<Empty>();
    Empty tmp735 = new Empty();

    tmp734.add(tmp735);

    COMPACT_TEST.setStruct_set(tmp734);
    Map<Byte,Byte> tmp736 = new HashMap<Byte,Byte>();
    tmp736.put((byte)1, (byte)2);

    COMPACT_TEST.setByte_byte_map(tmp736);
    Map<Short,Byte> tmp737 = new HashMap<Short,Byte>();
    tmp737.put((short)1, (byte)1);
    tmp737.put((short)-1, (byte)1);
    tmp737.put((short)32767, (byte)1);

    COMPACT_TEST.setI16_byte_map(tmp737);
    Map<Integer,Byte> tmp738 = new HashMap<Integer,Byte>();
    tmp738.put(1, (byte)1);
    tmp738.put(-1, (byte)1);
    tmp738.put(2147483647, (byte)1);

    COMPACT_TEST.setI32_byte_map(tmp738);
    Map<Long,Byte> tmp739 = new HashMap<Long,Byte>();
    tmp739.put(0L, (byte)1);
    tmp739.put(1L, (byte)1);
    tmp739.put(-1L, (byte)1);
    tmp739.put(9223372036854775807L, (byte)1);

    COMPACT_TEST.setI64_byte_map(tmp739);
    Map<Double,Byte> tmp740 = new HashMap<Double,Byte>();
    tmp740.put(-1.1, (byte)1);
    tmp740.put(1.1, (byte)1);

    COMPACT_TEST.setDouble_byte_map(tmp740);
    Map<String,Byte> tmp741 = new HashMap<String,Byte>();
    tmp741.put("first", (byte)1);
    tmp741.put("second", (byte)2);
    tmp741.put("third", (byte)3);
    tmp741.put("", (byte)0);

    COMPACT_TEST.setString_byte_map(tmp741);
    Map<Boolean,Byte> tmp742 = new HashMap<Boolean,Byte>();
    tmp742.put(true, (byte)1);
    tmp742.put(false, (byte)0);

    COMPACT_TEST.setBoolean_byte_map(tmp742);
    Map<Byte,Short> tmp743 = new HashMap<Byte,Short>();
    tmp743.put((byte)1, (short)1);
    tmp743.put((byte)2, (short)-1);
    tmp743.put((byte)3, (short)32767);

    COMPACT_TEST.setByte_i16_map(tmp743);
    Map<Byte,Integer> tmp744 = new HashMap<Byte,Integer>();
    tmp744.put((byte)1, 1);
    tmp744.put((byte)2, -1);
    tmp744.put((byte)3, 2147483647);

    COMPACT_TEST.setByte_i32_map(tmp744);
    Map<Byte,Long> tmp745 = new HashMap<Byte,Long>();
    tmp745.put((byte)1, 1L);
    tmp745.put((byte)2, -1L);
    tmp745.put((byte)3, 9223372036854775807L);

    COMPACT_TEST.setByte_i64_map(tmp745);
    Map<Byte,Double> tmp746 = new HashMap<Byte,Double>();
    tmp746.put((byte)1, 0.1);
    tmp746.put((byte)2, -0.1);
    tmp746.put((byte)3, 1e+06);

    COMPACT_TEST.setByte_double_map(tmp746);
    Map<Byte,String> tmp747 = new HashMap<Byte,String>();
    tmp747.put((byte)1, "");
    tmp747.put((byte)2, "blah");
    tmp747.put((byte)3, "loooooooooooooong string");

    COMPACT_TEST.setByte_string_map(tmp747);
    Map<Byte,Boolean> tmp748 = new HashMap<Byte,Boolean>();
    tmp748.put((byte)1, true);
    tmp748.put((byte)2, false);

    COMPACT_TEST.setByte_boolean_map(tmp748);
    Map<List<Byte>,Byte> tmp749 = new HashMap<List<Byte>,Byte>();
    List<Byte> tmp750 = new ArrayList<Byte>();
    tmp750.add((byte)1);
    tmp750.add((byte)2);
    tmp750.add((byte)3);

    tmp749.put(tmp750, (byte)1);
    List<Byte> tmp751 = new ArrayList<Byte>();
    tmp751.add((byte)0);
    tmp751.add((byte)1);

    tmp749.put(tmp751, (byte)2);
    List<Byte> tmp752 = new ArrayList<Byte>();

    tmp749.put(tmp752, (byte)0);

    COMPACT_TEST.setList_byte_map(tmp749);
    Map<Set<Byte>,Byte> tmp753 = new HashMap<Set<Byte>,Byte>();
    Set<Byte> tmp754 = new HashSet<Byte>();
    tmp754.add((byte)1);
    tmp754.add((byte)2);
    tmp754.add((byte)3);

    tmp753.put(tmp754, (byte)1);
    Set<Byte> tmp755 = new HashSet<Byte>();
    tmp755.add((byte)0);
    tmp755.add((byte)1);

    tmp753.put(tmp755, (byte)2);
    Set<Byte> tmp756 = new HashSet<Byte>();

    tmp753.put(tmp756, (byte)0);

    COMPACT_TEST.setSet_byte_map(tmp753);
    Map<Map<Byte,Byte>,Byte> tmp757 = new HashMap<Map<Byte,Byte>,Byte>();
    Map<Byte,Byte> tmp758 = new HashMap<Byte,Byte>();
    tmp758.put((byte)1, (byte)1);

    tmp757.put(tmp758, (byte)1);
    Map<Byte,Byte> tmp759 = new HashMap<Byte,Byte>();
    tmp759.put((byte)2, (byte)2);

    tmp757.put(tmp759, (byte)2);
    Map<Byte,Byte> tmp760 = new HashMap<Byte,Byte>();

    tmp757.put(tmp760, (byte)0);

    COMPACT_TEST.setMap_byte_map(tmp757);
    Map<Byte,Map<Byte,Byte>> tmp761 = new HashMap<Byte,Map<Byte,Byte>>();
    Map<Byte,Byte> tmp762 = new HashMap<Byte,Byte>();

    tmp761.put((byte)0, tmp762);
    Map<Byte,Byte> tmp763 = new HashMap<Byte,Byte>();
    tmp763.put((byte)1, (byte)1);

    tmp761.put((byte)1, tmp763);
    Map<Byte,Byte> tmp764 = new HashMap<Byte,Byte>();
    tmp764.put((byte)1, (byte)1);
    tmp764.put((byte)2, (byte)2);

    tmp761.put((byte)2, tmp764);

    COMPACT_TEST.setByte_map_map(tmp761);
    Map<Byte,Set<Byte>> tmp765 = new HashMap<Byte,Set<Byte>>();
    Set<Byte> tmp766 = new HashSet<Byte>();

    tmp765.put((byte)0, tmp766);
    Set<Byte> tmp767 = new HashSet<Byte>();
    tmp767.add((byte)1);

    tmp765.put((byte)1, tmp767);
    Set<Byte> tmp768 = new HashSet<Byte>();
    tmp768.add((byte)1);
    tmp768.add((byte)2);

    tmp765.put((byte)2, tmp768);

    COMPACT_TEST.setByte_set_map(tmp765);
    Map<Byte,List<Byte>> tmp769 = new HashMap<Byte,List<Byte>>();
    List<Byte> tmp770 = new ArrayList<Byte>();

    tmp769.put((byte)0, tmp770);
    List<Byte> tmp771 = new ArrayList<Byte>();
    tmp771.add((byte)1);

    tmp769.put((byte)1, tmp771);
    List<Byte> tmp772 = new ArrayList<Byte>();
    tmp772.add((byte)1);
    tmp772.add((byte)2);

    tmp769.put((byte)2, tmp772);

    COMPACT_TEST.setByte_list_map(tmp769);
  }

  public static final int MYCONST = 2;

  /**
   * This is a docstring on a constant!
   */
  public static final SomeEnum MY_SOME_ENUM = thrift.test.SomeEnum.ONE;

  public static final SomeEnum MY_SOME_ENUM_1 = thrift.test.SomeEnum.ONE;

  public static final Map<SomeEnum,SomeEnum> MY_ENUM_MAP = new HashMap<SomeEnum,SomeEnum>();
  static {
    MY_ENUM_MAP.put(thrift.test.SomeEnum.ONE, thrift.test.SomeEnum.TWO);
  }

  public static final Map<SomeEnum,StructWithSomeEnum> EXTRA_CRAZY_MAP = new HashMap<SomeEnum,StructWithSomeEnum>();
  static {
    StructWithSomeEnum tmp773 = new StructWithSomeEnum();
    tmp773.setBlah(thrift.test.SomeEnum.TWO);

    EXTRA_CRAZY_MAP.put(thrift.test.SomeEnum.ONE, tmp773);
  }

}
